### ISSUE TITLE
How to run in an Azure Function

### ISSUE THREAD

**Issue by keithf1138** [mattosaurus/PgpEncrypt#1]
Seems to be pretty simple and I have it working in a test client, when I move the code to encrypt into Azure Function and deploy I am getting "No encryption methods specified".  Wondering if the Azure Function needs to be configured with some extra permissions or something for this to work.

//_publicKey is a string holding the _publicKey
string encryptedContent;
EncryptionKeys encryptionKeys = new EncryptionKeys(_publicKey);
// Encrypt
PGP pgp = new PGP(encryptionKeys);

using (MemoryStream outputStream = new MemoryStream())
{
    // Encrypt
    using (MemoryStream inputStream = new MemoryStream(Encoding.UTF8.GetBytes(contents ?? "")))
    {
        await pgp.EncryptStreamAsync(inputStream, outputStream);
        encryptedContent = System.Text.Encoding.UTF8.GetString(outputStream.ToArray());
    }
}

**Comment by mattosaurus** [comment]
So the example here works so maybe you can just copy that.

https://github.com/mattosaurus/PgpEncrypt/blob/d4133f513b7ec4e0e00b7f0158f49d76c2d7c24f/PgpEncrypt.Function/PgpFunction.cs#L26-L49

You shouldn't need any additional permissions to do this in Azure though it's possible you're not publishing your public key which might be causing issues.

**Comment by keithf1138** [comment]
That's what I modeled my code off of. Only thing different is that I load the public key from a string in configuration rather than reading from a file.

If I was to switch from the string to the file where do I put the public key file in Azure and how do I get the file in that location?

**Comment by keithf1138** [comment]
Only real difference is that I am not using the public key in a file. I put the public key in configuration. Could that be the issue? Where in the Azure function project should I put the key files? Then how to access them from the function?

**Comment by keithf1138** [comment]
Turns out the issue was having the key in a string. Once I loaded from a file the issue went away. Dont know if simply because it was in a string or was the string in some wrong format because it was stored in Azure Configuration.
